#!/bin/bash 
#SBATCH -n 4                    # Number of cores
#SBATCH --mem 24000             # 16GB asked
#SBATCH -p mlow                # Choose mlow to submit to master low prioriy queue
#SBATCH --gres gpu:1            # To ask Pascales MAX 8
#SBATCH -o logs/log_%u_%j.out   # File to which STDOUT will be written
#SBATCH -e logs/log_%u_%j.err   # File to which STDERR will be written

python main_spotting.py --model E2_TCN8_NMS_hard_w3_th_005
python main_spotting.py --model E2_TCN8_NMS_hard_w7_th_005
python main_spotting.py --model E2_TCN8_NMS_hard_w10_th_003_mean_smooth_sw5
python main_spotting.py --model E2_TCN8_NMS_hard_w10_th_003_mean_smooth_sw7

