#!/bin/bash 
#SBATCH -n 4                    # Number of cores
#SBATCH --mem 24000             # 16GB asked
#SBATCH -p mlow                # Choose mlow to submit to master low prioriy queue
#SBATCH -o logs/log_%u_%j.out   # File to which STDOUT will be written
#SBATCH -e logs/log_%u_%j.err   # File to which STDERR will be written

python main_spotting.py --model baseline