#!/bin/bash 
#SBATCH -n 4                    # Number of cores
#SBATCH --mem 20000             # 16GB asked
#SBATCH -p mlow                # Choose mlow to submit to master low prioriy queue
#SBATCH -q masterhigh           # Requeue other users mlow jobs
#SBATCH --gres gpu:1            # To ask Pascales MAX 8
#SBATCH -o logs/log_%u_%j.out   # File to which STDOUT will be written
#SBATCH -e logs/log_%u_%j.err   # File to which STDERR will be written

# python main_classification.py --model BEST_with_temp_shift
python main_classification.py --model multiclip_max_BEST_s4_3windows

